### ISSUE TITLE
How can one install this?

### ISSUE THREAD

**Issue by felixprojekt** [mattchanner/darkula#7]
After installing from Package Control, nothing happens - Sublime Text 3 (Build 3207). Tried restarting.

How exactly should Option 1 work?

Thanks

**Comment by mattchanner** [comment]
Did you try switching to the scheme once it was installed?

Under the Preferences menu, select *Color Scheme* then locate select the *darkula* scheme to enable it

**Comment by felixprojekt** [comment]
I guess I need a holiday, see it now 😄

Great work, thanks
